### ISSUE TITLE
Kanban board setup

### ISSUE THREAD

**Issue by tomasesquivelgc** [fmanimashaun/book-car#11]
For this group we are 5 people and decided to use 2 repos, one for back-end and the other for the front-end. We also created 2 separate  kanban boards for their respective repos.

Back-end kanban board:
https://github.com/users/fmanimashaun/projects/16/views/1
![image](https://github.com/fmanimashaun/book-car/assets/117373513/dbbfe0fa-1c7c-4c9f-9406-ba8e2cb6b378)

Front-end kanban board:
https://github.com/users/fmanimashaun/projects/15/views/1
![image](https://github.com/fmanimashaun/book-car/assets/117373513/c05b8468-ea3a-4107-adc1-af495c565b82)

**Comment by Meltrust** [comment]
Hi,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



### To highlight:

- All tasks have assignees.✔️ 

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

## Required Changes ♻️

- [ ] According to the project [requirements](https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/setup_kanban_board.md):

![image](https://github.com/fmanimashaun/book-car/assets/57421823/947b9c7e-9d2b-4df7-a154-c2ceee143e5e)

At the time of this review, these are the pointings adding up the 2 kanban boards:

tomasesquivelgc 15+18=23
simplegoose 13+17=30
M-Anwar-Hussaini 17+10=27
fmanimashaun 16+6=22
Estete9 21+9=30

As you can see, @fmanimashaun and @tomasesquivelgc have a lot less points than the other team members.

The general rule is "nobody should have 5 points more than any other member of the team".

Kindly, make sure your project meets this particular requirement.

_tip:  You'll need to count the points to ensure the rule is met._

_another tip for the future:  In the industry, we never use multiple Kanban boards for a single project, even if it spans multiple apps and repos._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by tomasesquivelgc** [comment]
# Re-submission:
Tasks have been distributed differently to comply with the previous review.

## Back-end kanban:
https://github.com/users/fmanimashaun/projects/16/views/1
![image](https://github.com/fmanimashaun/book-car/assets/117373513/60ab4a1c-d144-44ba-9baa-c92c07ab3829)

## Front-end kanban:
https://github.com/users/fmanimashaun/projects/15/views/1
![image](https://github.com/fmanimashaun/book-car/assets/117373513/a735272d-e9d1-41ee-ab8a-532424219090)

**Comment by Meltrust** [comment]
## Wow, you did it 🎉
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for implementing the changes requested by the previous reviewer 💪 🥇 ㊗️ 
### Well done!




Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- Pointings are now equal✔️ 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
